# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7.13
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4


    steps:
      - checkout

     

      - run:
          name: install dependencies
          command: |
            #python3 -m venv venv
            #. venv/bin/activate
            pip --version
            sudo pip install -r requirements.txt


        
      # run tests!
      - run:
          name: run tests
          command: |
            #. venv/bin/activate
            python --version
            python -m unittest Persontest
          
          name: coverage and reports
          command: |
            #. venv/bin/activate
            coverage run Person.py 
            coverage report
            coveralls

      - store_artifacts:
          path: test-reports
          destination: test-reports
          